# Generated by Django 2.1.7 on 2019-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_number', models.CharField(max_length=2)),
                ('trailer_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Empty', 'Empty'), ('Loaded', 'Loaded'), ('In Progress', 'In Progress'), ('None', 'None')], default='4', max_length=20)),
            ],
        ),
    ]
