# Generated by Django 2.1.7 on 2019-04-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='trailer_number',
            field=models.CharField(default='No Trailer', max_length=100),
        ),
    ]
