# Generated by Django 2.1.7 on 2019-04-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailerapp', '0003_auto_20190430_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Loaded', 'Loaded'), ('In Progress', 'In Progress'), ('Empty', 'Empty')], default='3', max_length=20),
        ),
    ]
