# Generated by Django 2.1.7 on 2019-04-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailerapp', '0004_auto_20190430_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='door_number',
            field=models.IntegerField(),
        ),
    ]
